name       : makemkv
version    : 1.12.0
release    : 6
source     :
    - https://www.makemkv.com/download/makemkv-oss-1.12.0.tar.gz : 18ede2b55cfb76b726a9121eaf47f8fc41ee4eff3870ac5d1fd4054d7eade2b3
    - https://www.makemkv.com/download/makemkv-bin-1.12.0.tar.gz : 6d1b1c7ef835c8ce639ea9d24cb89829049349e85e2c381723bada0e4733f498
license    :
    - GPL-2.0
    - LGPL-2.0
    - Distributable
component  : multimedia.video
summary    : MakeMKV video transcoder
description: |
    MakeMKV is your one-click solution to convert video that you own into free and patents-unencumbered format that can be played everywhere.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libavcodec)
strip      : no
setup      : |
    tar xvf $sources/makemkv-bin-${version}.tar.gz
    %configure
build      : |
    %make
install    : |
    # build oss package
    %make_install

    # build bin package
    pushd "makemkv-bin-${version}"
    mkdir tmp
    echo accepted > tmp/eula_accepted
    %make_install
    popd

    # Ensure license is shipped in accordance with redistribution terms
    # and that the package is unmodified, by not stripping the binaries
    # See: strip: no
    install -D -m 00644 makemkv-bin-${version}/src/eula_en_linux.txt $installdir/usr/share/doc/${package}/eula_en_linux.txt

