name       : makemkv
version    : 1.10.8
release    : 5
source     :
    - https://www.makemkv.com/download/makemkv-oss-1.10.8.tar.gz : d17cfd916a9bdda35b1065bce86a48a987caf9ffb4d6861609458f9f312603c7
    - https://www.makemkv.com/download/makemkv-bin-1.10.8.tar.gz : b7861aa7b03203f50d2ce3130f805c4b0406d13aec597648050349fa8b084b29
license    :
    - GPL-2.0
    - LGPL-2.0
    - Distributable
component  : multimedia.video
summary    : MakeMKV video transcoder
description: |
    MakeMKV is your one-click solution to convert video that you own into free and patents-unencumbered format that can be played everywhere.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libavcodec)
strip      : no
setup      : |
    tar xvf $sources/makemkv-bin-${version}.tar.gz
    %configure
build      : |
    %make
install    : |
    # build oss package
    %make_install

    # build bin package
    pushd "makemkv-bin-${version}"
    mkdir tmp
    echo accepted > tmp/eula_accepted
    %make_install
    popd

    # Ensure license is shipped in accordance with redistribution terms
    # and that the package is unmodified, by not stripping the binaries
    # See: strip: no
    install -D -m 00644 makemkv-bin-${version}/src/eula_en_linux.txt $installdir/usr/share/doc/${package}/eula_en_linux.txt
