name       : makemkv
version    : 1.10.7
release    : 4
source     :
    - https://www.makemkv.com/download/makemkv-oss-1.10.7.tar.gz : be61fcee31dc52944ec7ef440ff8fffbc140d24877e6afb19149c541564eb654
    - https://www.makemkv.com/download/makemkv-bin-1.10.7.tar.gz : 2b9a9e6fb779bc876371b2f88b23fddad3e92d6449fe5d1541dcd9ad04e01eac
license    :
    - GPL-2.0
    - LGPL-2.0
    - Distributable
component  : multimedia.video
summary    : MakeMKV video transcoder
description: |
    MakeMKV is your one-click solution to convert video that you own into free and patents-unencumbered format that can be played everywhere.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libavcodec)
strip      : no
setup      : |
    tar xvf $sources/makemkv-bin-${version}.tar.gz
    %configure
build      : |
    %make
install    : |
    # build oss package
    %make_install

    # build bin package
    pushd "makemkv-bin-${version}"
    mkdir tmp
    echo accepted > tmp/eula_accepted
    %make_install
    popd

    # Ensure license is shipped in accordance with redistribution terms
    # and that the package is unmodified, by not stripping the binaries
    # See: strip: no
    install -D -m 00644 makemkv-bin-${version}/src/eula_en_linux.txt $installdir/usr/share/doc/${package}/eula_en_linux.txt
