name       : makemkv
version    : 1.12.2
release    : 7
source     :
    - https://www.makemkv.com/download/makemkv-oss-1.12.2.tar.gz : 611b3012419e1f51df43cd74fd3048ccb2e9b9225642af3dff04ae8fd07a7918
    - https://www.makemkv.com/download/makemkv-bin-1.12.2.tar.gz : f2fa5cc2fe2f8e1bdcb19533ddd20d382829012e651103bc2f559973005e9e7a
license    :
    - GPL-2.0
    - LGPL-2.0
    - Distributable
component  : multimedia.video
summary    : MakeMKV video transcoder
description: |
    MakeMKV is your one-click solution to convert video that you own into free and patents-unencumbered format that can be played everywhere.
builddeps  :
    - pkgconfig(Qt5Core)
    - pkgconfig(libavcodec)
strip      : no
setup      : |
    tar xvf $sources/makemkv-bin-${version}.tar.gz
    %configure
build      : |
    %make
install    : |
    # build oss package
    %make_install

    # build bin package
    pushd "makemkv-bin-${version}"
    mkdir tmp
    echo accepted > tmp/eula_accepted
    %make_install
    popd

    # Ensure license is shipped in accordance with redistribution terms
    # and that the package is unmodified, by not stripping the binaries
    # See: strip: no
    install -D -m 00644 makemkv-bin-${version}/src/eula_en_linux.txt $installdir/usr/share/doc/${package}/eula_en_linux.txt

